### ISSUE TITLE
KSP2 Forum Thread

### ISSUE THREAD

**Issue by schlosrat** [Micrologist/MicroEngineer#12]
Hi, I was wondering if you wouldn't mind creating a forum thread for this in https://forum.kerbalspaceprogram.com/index.php?/forum/130-ksp2-mod-releases/? This would be a great place for you to announce new features and updates, and for users to be able to discuss how to use the mod. Also, I'd like to be able to link to that when giving credit for your work that I've liberally "borrowed" in making my mod.

**Comment by Falki-git** [comment]
Added to the forum: https://forum.kerbalspaceprogram.com/index.php?/topic/215989-micro-engineer/
