### ISSUE TITLE
[FEATURE] Persistent window(s) position and state

### ISSUE THREAD

**Issue by Falki-git** [Micrologist/MicroEngineer#5]
Currently exiting the game and loading again resets evrything.

**Comment by Micrologist** [comment]
Currently waiting on the spacewarp bepinex conversion before looking into any kind of persistent settings storage. As soon as that's done, I'll get on that.

**Comment by Falki-git** [comment]
https://github.com/Micrologist/MicroEngineer/pull/7 - Helped by adding persistence by saving states in a json file. Hope it's ok.

**Comment by Micrologist** [comment]
Thanks, will put that into the next release!
