### ISSUE TITLE
[FEATURE] Target phase angle 

### ISSUE THREAD

**Issue by Pac2dev** [Micrologist/MicroEngineer#9]
Love the mod so far but could phase angle be added to the target section?

**Comment by Falki-git** [comment]
It's possible, yes. If @Micrologist doesn't take this up, I could do it, but a bit later as I'm working on a project at the moment.

In the meantime, there's already a mod that does just that: https://spacedock.info/mod/3297/Transfer%20Window

**Comment by Pac2dev** [comment]
> It's possible, yes. If @Micrologist doesn't take this up, I could do it, but a bit later as I'm working on a project at the moment.
> 
> In the meantime, there's already a mod that does just that: https://spacedock.info/mod/3297/Transfer%20Window

Thanks, that mod works well if you are targeting a planet but I was hoping to use it for a satellite network.

**Comment by Pac2dev** [comment]
> I'm not entirely sure how to calculate that, I'll look into it if anyone has any pointers.

Not sure about the math on it but I used to use kerbal engineer redux on ksp1 for it and I think they eventually added it to the base game.

**Comment by Falki-git** [comment]
Done in https://github.com/Micrologist/MicroEngineer/pull/23
